### PR TITLE
fix: data race on shouldContinue

### LINKED ISSUE #5: Bug: data race on core.shouldContinue between Run() and Stop()
**Describe the bug**
`core.shouldContinue` is a plain `bool` that is read in `Run()`'s loop and written by `Stop()` without synchronization. Every realistic caller invokes `Stop()` from a different goroutine than the one running `Run()` - including the library's own `gracefulshutdown` middleware, which calls `Stop()` from the signal-handling goroutine. This is a data race under the Go memory model; `go test -race` flags it, and in principle the loop is not guaranteed to observe the `Stop()` store and terminate.

**To Reproduce**
<details>
    <summary>Steps to reproduce</summary>

  ```go
  package main
                                                                                                                                                                     
  import (
        "context"                                                                                                                                                    
        "testing"                        
        "time"                           

        "github.com/messaging-go/core"
  )

  func TestRaceStop(t *testing.T) {
        p := core.New[int](func(error) {})                                                                                                                           
   
        go func() {                                                                                                                                                  
                time.Sleep(10 * time.Millisecond)                                                                                                                    
                p.Stop()                 
        }()                                                                                                                                                          
                                         
        p.Run(func(ctx context.Context, item *int) error { return nil })
  }                                                                                                                                                                  
  ```
                                                                                                                                                                     
  Run with:                              
  ```                                    
  go test -race -run TestRaceStop
  ```                                                                                                                                                                
  </details>

**Expected behavior**
`Run()` observes `Stop()` and returns cleanly, with no race reported by the detector.

**Screenshots**
N/A

**Observed behavior**
`go test -race` reports a data race (flaky - not every run trips the detector, but `go test -race -count=20` reliably produces at least one DATA RACE report; verified on v1.0.2 / Go 1.25.0 / macOS arm64):                          
                                                                                                                                                                                                                                        
  ```                                                                                                                                                                                                                                   
  WARNING: DATA RACE                                                                                                                                                                                                                    
  Write at 0x... by goroutine 8:                                                                                                                                                                                                        
    github.com/messaging-go/core.(*core[...]).Stop()                                                                                                                                                                                    
        core.go:27                                                                                                                                                                                                                      
    ...TestRaceStop.func2()                                                                                                                                                                                                             
                                                                                                                                                                                                                                        
  Previous read at 0x... by goroutine 7: 
    github.com/messaging-go/core.(*core[...]).Run()                                                                                                                                                                                     
        core.go:14                                                                                                                                                                                                                      
    ...TestRaceStop()                    
  ```                                                                                                                                                                                                                                   
              
  The flakiness is why the existing test suite on main passes despite the bug, the read and write don't interleave on every sample.                                                                                                    
   
  The same race is reachable through the public API via the built-in `gracefulshutdown` middleware, which calls `core.Stop()` from its signal-handling goroutine (`middlewares/gracefulshutdown/shutdown.go:29`). Any user of that middleware is affected.

**Environment**
 - OS: macOS (also reproducible on linux)
 - Version: v1.0.2                       
 - Go version: 1.25.0 (as pinned in `go.mod`)

**Logs**
N/A

**Additional context**
Proposed fix: promote `shouldContinue` from `bool` to `sync/atomic.Bool`, using `Load()` in `Run()` and `Store(false)` in `Stop()`. Minimal change, keeps the public API unchanged, satisfies the backwards-compat guarantee in  `CONTRIBUTING.md`.                                                                                                                                                                                                                    
                                                                                                                                                                                                                                        
  Two related findings worth tracking alongside:                                                                                                                                                                                        
  - The CI test step in `.github/workflows/build.yaml.yml` does not pass `-race`, which is why this class of bug can regress silently. Adding `-race` would have caught it.                                                             
  - Once `-race` is enabled in CI, a pre-existing race in `middlewares/gracefulshutdown/shutdown_test.go` surfaces (the `called` flag is written in one goroutine and asserted in another with only `time.Sleep` for synchronization).  
  Unrelated production-wise, but blocks turning `-race` on.

### PR DESCRIPTION
**Pull request by skartikey**
## Pull Request Checklist

Please confirm that you have done the following:

- [x] I have confirmed that the PR type is appropriate for the change I am making according to
  the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) file.
- [x] I have added tests for all code changes.

Link to documentation changes:
### Description
  - `core.shouldContinue` promoted from plain `bool` to `sync/atomic.Bool`. `Run()` uses `Load()`, `Stop()` uses `Store(false)`. Public API is unchanged, so the backwards-compat guarantee in `CONTRIBUTING.md` holds.
  - Pre-existing race in `middlewares/gracefulshutdown/shutdown_test.go` fixed: the `called` flag is now `atomic.Bool`, so the write from the middleware goroutine and the read from the assertion are synchronized. Unrelated to       
  production behavior, but it surfaces once `-race` is enabled in CI.                                                                                                                                                            
  - CI test step updated to pass `-race`, so regressions in this class of bug are caught automatically.

closes #5

### CODE REVIEW

File: core.go [hunk 1]
```diff
@@ -24,13 +24,15 @@ func (c *core[MessageType]) AddMiddleware(middleware Middleware[*MessageType]) M
...
 }
 
 func New[MessageType any](resultsObserver func(error)) MessageProcessor[MessageType] {
-	return &core[MessageType]{
+	instance := &core[MessageType]{
 		chain:           middleware.New[*MessageType, error](),
-		shouldContinue:  true,
 		resultsObserver: resultsObserver,
 	}
+	instance.shouldContinue.Store(true)
```
Comment (cyberhck) [inline core.go:35]: we can do this in place:
```go
shouldContinue: atomic.NewBool(true)
```

**Review by cyberhck — COMMENTED** [review]
can we do one liner change here? :)

File: core.go (hunk 1 above)
Comment (cyberhck) [reply core.go:35]: never mind, wrong package.

**Review by cyberhck — APPROVED** [review]
